Repository joakimAbdinurIusuf/DECIDE, pull requests merged in 2022-02, with the labels that each got.

#70 Issue#3 Implements LIC1 method and unit tests
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#75 feat: Adds .DS_Store to .gitignore.
  .gitignore
Labels: enhancement

#79 issue#78 Removes unnecessary .DS_Store file
  .DS_Store
Labels: refactor

#73 issue#53 refactors LIC0() to call the helper method distanceBetween2Points()
  src/main/java/Decide.java
Labels: refactor

#72 Adds test to the PUM function
  src/main/java/Decide.java
  src/main/java/LCM.java
  src/test/java/DecideTest.java
Labels: testing

#71 FUV function
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#88 Issue#86 Adds java doc to methods that weren't commented
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: documentation
