Repository joakimAbdinurIusuf/DECIDE, pull requests merged in 2022-01, with the labels that each got.

#54 Issue#15 Implements LIC14 and unit tests
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#59 Issue#8 Implements LIC2 and unit tests
  build.gradle
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#60 Issue#9 Implements LIC7 and unit tests
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#69 issue#56 modifies LIC3() to call the helper method triangleArea()
  src/main/java/Decide.java
Labels: refactor

#68 issue#57 Fixes typo in documentation for LIC14PositiveCase()
  src/test/java/DecideTest.java
Labels: documentation

#66 Updates to the README file
  README.md
Labels: documentation

#58 Issue#11 Implements LIC12 and unit tests
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement

#67 Issue#19 Implements LIC10 and unit tests
  src/main/java/Decide.java
  src/test/java/DecideTest.java
Labels: enhancement
